version: '3'
services:
  database:
    image: mysql:5.7
    container_name: docker-mysql
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ~/home/sidney/Documents/Trybe/HardSkills/Trybe-exercices/BackEnd/02.SQL:/var/lib/mysql
